language: node_js
node_js:
- stable
env:
  global:
  - COMMIT_AUTHOR_EMAIL: ci@md-systems.ch
before_install:
- openssl aes-256-cbc -K $encrypted_cafcdd94244e_key -iv $encrypted_cafcdd94244e_iv
  -in scripts/deploy_key.enc -out scripts/deploy_key -d
- sudo apt-get -qq update
- sudo apt-get install -y calibre xvfb
script: bash ./scripts/deploy.sh
